language: python
python:
  - 2.7
  - 3.3
  - 3.5
install: pip install tox
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.3
      env: TOX_ENV=py33
    - python: 3.5
      env: TOX_ENV=py35
script:
  - env
  - tox -e "${TOX_ENV}"
