language: python
python:
  - 2.7
  - 3.3
  - 3.5
#install: pip install -r requirements.txt # default
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then py.test --lf -k Unit; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then py.test --lf -k Unit; fi
